# Generated by Django 5.1.7 on 2025-03-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4, verbose_name='скидка'),
        ),
    ]
