# Generated by Django 5.1.7 on 2025-04-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
